# Generated by Django 3.1.5 on 2021-02-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0002_auto_20210228_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
